name: Build & deploy images to Docker Registry

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PB_VERSION: '0.25.2'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          file: ${{ env.DOCKER_FILE }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          
          build-args: |
            VERSION=${{ env.PB_VERSION }}
          # build-args: VERSION=${{ steps.version.outputs.value }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.PB_VERSION }}
            ghcr.io/${{ github.repository }}:latest
            ${{ github.repository }}:${{ env.PB_VERSION }}
            ${{ github.repository }}:latest
          cache-from: type=registry,ref=${{ github.repository	}}:latest
          cache-to: type=inline
